# config.yaml

# Cron pattern (runs every minutes)
cron_schedule: "* * * * *"

# Database Configuration
database_filepath: "data/data.db"

#  GitHub Credentials
github_username: github_username
github_token: "github_pat_token"
github_email: "xyz@gmail.com"

# Google Drive Credentials
google_drive_credentials_filepath: "google-drive-credentials.json"
